name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vitepress/dist
        
